"""
HARFNEWS Zero-Shot Evaluation with GPT-5-mini-2025-08-07
=========================================================
학습(train) 없이 OpenAI Vision API를 이용한 zero-shot 4-way 분류 평가.
클래스: HR (Human Real) / HF (Human Fake) / AR (AI Real) / AF (AI Fake)

   - 중간 저장(체크포인트) 지원: 중단 후 재실행하면 완료된 샘플 자동 스킵
   - Rate Limit 자동 대기 및 재시도
   - 비용 사전 추정 출력

사용법:
    export OPENAI_API_KEY="sk-..."
    python harfnet_zeroshot_gpt5mini.py [--options]

주요 옵션:
    --csv_path        HARFM.csv 경로
    --data_root       이미지 루트 경로
    --output_dir      결과 저장 디렉터리
    --concurrency     병렬 요청 수 (기본: 8, Rate Limit 고려해 조정)
    --checkpoint_every  N개 완료마다 중간 저장 (기본: 100)
    --resume          기존 체크포인트 이어받기 (기본: True)
    --no_resume       체크포인트 무시하고 처음부터 재실행
    (API 키는 코드 상단 OPENAI_API_KEY 변수에 직접 입력)
"""

from __future__ import annotations

import argparse
import asyncio
import base64
import io
import json
import os
import random
import sys
import time
import warnings
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, Tuple

warnings.filterwarnings("ignore")

# ── .env 파일에서 API 키 자동 로드 ──────────────────────────────
try:
    from dotenv import load_dotenv
    # 스크립트 위치 → 상위 폴더 순으로 .env 탐색
    _env_candidates = [
        Path(__file__).parent / ".env",
        Path(__file__).parent.parent / ".env",
        Path.cwd() / ".env",
    ]
    for _ep in _env_candidates:
        if _ep.is_file():
            load_dotenv(_ep, override=False)  # 이미 설정된 환경변수는 덮어쓰지 않음
            print(f"[ZeroShot] .env 로드: {_ep}")
            break
except ImportError:
    pass  # python-dotenv 없으면 환경변수에서 직접 읽음

import numpy as np
import pandas as pd
from PIL import Image
from openai import AsyncOpenAI
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    f1_score,
    roc_auc_score,
)
from sklearn.model_selection import train_test_split
from tqdm import tqdm

# ─────────────────────────────────────────────────────────────
# 상수
# ─────────────────────────────────────────────────────────────
MODEL_NAME  = "gpt-5-mini-2025-08-07"
CLASS_NAMES = ["HR", "HF", "AR", "AF"]
CLASS2IDX   = {c: i for i, c in enumerate(CLASS_NAMES)}
IDX2CLASS   = {i: c for c, i in CLASS2IDX.items()}

_SCRIPT_DIR       = os.path.dirname(os.path.abspath(__file__))
_FND_ROOT = os.path.abspath(os.path.join(_SCRIPT_DIR, ".."))
DEFAULT_DATA_ROOT = _FND_ROOT
DEFAULT_CSV_PATH  = os.path.join(_FND_ROOT, "HARFM.csv")
DEFAULT_OUTPUT    = os.path.join(_SCRIPT_DIR, "results_zeroshot")

SEED = 42
TEST_RATIO = 0.2
IMAGE_SIZE = 224
MAX_COMPLETION_TOKENS = 1024       # gpt-5-mini reasoning 포함 기본 한도
MAX_COMPLETION_TOKENS_HIGH = 2048  # 출력 잘림 시 상향 재시도


def _tqdm_disable() -> bool:
    return os.environ.get("GPT_NO_TQDM", "").lower() in ("1", "true", "yes")


def _tqdm_file():
    """tee(2>&1) 로그에는 progress bar 미기록, 터미널(/dev/tty)에만 표시."""
    if _tqdm_disable():
        return None
    try:
        return open("/dev/tty", "w")
    except OSError:
        return None


class _TqdmNoOp:
    def update(self, n: int = 1) -> None:
        pass

    def close(self) -> None:
        pass


def _tqdm(*args, **kwargs):
    if _tqdm_disable():
        return _TqdmNoOp() if not args else args[0]
    fout = _tqdm_file()
    if fout is None:
        return _TqdmNoOp() if not args else args[0]
    kwargs.setdefault("file", fout)
    kwargs.setdefault("dynamic_ncols", True)
    return tqdm(*args, **kwargs)


# ── API 키 (직접 입력) ──────────────────────────────────────
OPENAI_API_KEY = "YOUR OPEN AI API KEY"

# ─────────────────────────────────────────────────────────────
# Zero-Shot 프롬프트 (멀티모달 전용)
# ─────────────────────────────────────────────────────────────
SYSTEM_PROMPT = """You are an expert multimodal news analyst specializing in detecting AI-generated content and misinformation.

You will be given a news headline AND its accompanying image. Analyze BOTH together to classify the article.

Your task is to classify news articles into one of four categories based on:
1. **Authorship**: Was the article written by a Human (H) or generated by AI (A)?
2. **Veracity**: Is the content Real/true (R) or Fake/false (F)?

**The four classes are:**
- **HR** (Human-Real): Written by a human, content is factually true/real
- **HF** (Human-Fake): Written by a human, content is false/fabricated/misleading
- **AR** (AI-Real): Generated by AI, content is factually true/real
- **AF** (AI-Fake): Generated by AI, content is false/fabricated/misleading

**Multimodal classification guidelines:**

[Text signals — Authorship]
- AI-written: formulaic phrasing, syntactically perfect, unnaturally uniform sentence structure
- Human-written: idiosyncratic style, colloquialisms, minor grammatical quirks, emotional variance

[Text signals — Veracity]
- Fake: sensational/emotional language, unverifiable claims, logical inconsistencies, misleading framing
- Real: neutral tone, verifiable facts, specific and consistent details

[Image signals — Authorship]
- AI-generated images: overly smooth textures, unnatural lighting, distorted fine details (hands, text, faces), surreal perfection
- Real photos: natural noise, authentic lighting, consistent perspective

[Image signals — Veracity]
- Image-headline mismatch: image context contradicts or is unrelated to the headline claim
- Manipulated images: artifacts, inconsistent shadows/reflections, blurred edges around objects

[Cross-modal signals]
- AF (most dangerous): fluent AI text + AI-generated or manipulated image, strong surface consistency but factually wrong
- HF: human-style text with a misleading or mismatched real photo
- AR: AI-generated text that accurately describes real, verifiable events with a genuine photo
- HR: human-written text with an authentic photo that matches the story

You MUST respond with ONLY a JSON object in this exact format:
{"label": "<HR|HF|AR|AF>", "confidence": <0.0-1.0>, "reasoning": "<2-3 sentence explanation citing both text and image cues>"}

Do not include any other text outside the JSON object."""


def build_user_message(headline: str, image_b64: str) -> list:
    """멀티모달 메시지 구성 — 이미지 + 헤드라인 항상 함께 전송"""
    text_content = (
        f"Analyze the following news article using BOTH the headline and the image.\n\n"
        f"**Headline:** {headline}\n\n"
        f"Consider: (1) writing style clues for authorship, "
        f"(2) factual plausibility of the claim, "
        f"(3) image authenticity and quality, "
        f"(4) consistency between the image and the headline.\n\n"
        f"Respond ONLY with the JSON object."
    )
    return [
        {
            "role": "user",
            "content": [
                {"type": "text", "text": text_content},
                {
                    "type": "image_url",
                    "image_url": {
                        "url": f"data:image/jpeg;base64,{image_b64}",
                        "detail": "auto",   # 중간 품질 — 이미지 해상도에 맞게 자동 결정
                    },
                },
            ],
        }
    ]


# ─────────────────────────────────────────────────────────────
# ─────────────────────────────────────────────────────────────
def resolve_image_path(p: str, data_root: str) -> str:
    p = (p or "").strip()
    if not p:
        return p
    if os.path.isabs(p) and os.path.isfile(p):
        return p
    return os.path.join(os.path.abspath(data_root), p)


def load_dataset(csv_path: str, data_root: str, seed: int = SEED) -> pd.DataFrame:
    """HARFM.csv 로딩 — 이미지+텍스트 둘 다 존재하는 전체 샘플 (멀티모달 전용)"""
    print(f"[ZeroShot] CSV 로딩: {csv_path}")
    df = pd.read_csv(
        csv_path,
        usecols=["final_headline", "image_path", "4_way_label"],
        low_memory=False,
    )
    df = df.dropna(subset=["final_headline", "4_way_label"])
    for c in ["final_headline", "image_path", "4_way_label"]:
        df[c] = df[c].fillna("").astype(str).str.strip()

    # 유효 레이블만
    df = df[df["4_way_label"].isin(CLASS_NAMES)].reset_index(drop=True)
    n_before = len(df)

    # 멀티모달 필터: 이미지 파일 실제 존재 + 헤드라인 비어있지 않음
    print(f"[ZeroShot] 이미지 경로 유효성 검사 중 ({n_before}행)...")

    def is_multimodal(row) -> bool:
        if not row["final_headline"]:
            return False
        rel = row["image_path"]
        if not rel:
            return False
        full = resolve_image_path(rel, data_root)
        return bool(full) and os.path.isfile(full)

    valid_mask = []
    for row in _tqdm(df.itertuples(), total=n_before, desc="  이미지 유효성 검사"):
        valid_mask.append(is_multimodal(row._asdict()))

    df = df[valid_mask].reset_index(drop=True)
    n_after = len(df)

    label_counts = df["4_way_label"].value_counts().to_dict()
    print(f"[ZeroShot] {n_before}행 → 멀티모달 유효 {n_after}행 "
          f"({n_before - n_after}행 스킵)")
    print(f"[ZeroShot] 레이블 분포: {label_counts}")

    if n_after == 0:
        raise ValueError(
            "멀티모달 유효 샘플 없음. --csv_path / --data_root 확인 필요."
        )

    return df


def split_test_indices(labels: List[int], seed: int = SEED) -> List[int]:
    """..."""
    idx = np.arange(len(labels))
    y   = np.array(labels)
    _, te, _, _ = train_test_split(
        idx, y, test_size=TEST_RATIO, stratify=y, random_state=seed,
    )
    return te.tolist()


def preprocess_image_harfnet(img: Image.Image, size: int = IMAGE_SIZE) -> Image.Image:
    """짧은 변 224 리사이즈 후 CenterCrop 224."""
    w, h = img.size
    if w < h:
        new_w, new_h = size, int(round(h * size / w))
    else:
        new_w, new_h = int(round(w * size / h)), size
    img = img.resize((new_w, new_h), Image.LANCZOS)
    left = (new_w - size) // 2
    top  = (new_h - size) // 2
    return img.crop((left, top, left + size, top + size))


def load_image_b64(image_path: str, data_root: str,
                   size: int = IMAGE_SIZE) -> Optional[str]:
    """이미지를"""
    try:
        full = resolve_image_path(image_path, data_root)
        if not full or not os.path.isfile(full):
            return None
        img = preprocess_image_harfnet(Image.open(full).convert("RGB"), size=size)
        buf = io.BytesIO()
        img.save(buf, format="JPEG", quality=90)
        return base64.b64encode(buf.getvalue()).decode("utf-8")
    except Exception as e:
        print(f"  [경고] 이미지 로드 실패 ({image_path}): {e}", file=sys.stderr)
        return None


# ─────────────────────────────────────────────────────────────
# 체크포인트 (중간 저장 / 이어받기)
# ─────────────────────────────────────────────────────────────
class CheckpointManager:
    """완료된 샘플을 JSONL 파일에 한 줄씩 즉시 저장.
    재실행 시 이미 완료된 idx는 자동 스킵.
    """

    def __init__(self, ckpt_path: str):
        self.ckpt_path = ckpt_path
        self._done: Dict[int, dict] = {}  # idx → result
        self._lock = asyncio.Lock()

    def load(self) -> int:
        """기존 체크포인트 로드. 완료된 샘플 수 반환."""
        if not os.path.isfile(self.ckpt_path):
            return 0
        loaded = 0
        with open(self.ckpt_path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    r = json.loads(line)
                    self._done[r["idx"]] = r
                    loaded += 1
                except Exception:
                    continue
        return loaded

    def is_done(self, idx: int) -> bool:
        return idx in self._done

    def get_done(self, idx: int) -> Optional[dict]:
        return self._done.get(idx)

    async def save_one(self, result: dict):
        """결과 한 건을 JSONL에 즉시 append (thread-safe)."""
        async with self._lock:
            self._done[result["idx"]] = result
            with open(self.ckpt_path, "a", encoding="utf-8") as f:
                f.write(json.dumps(result, ensure_ascii=False) + "\n")

    def all_results(self, total_idx: List[int]) -> List[dict]:
        """idx 순서대로 결과 반환."""
        return [self._done[i] for i in total_idx if i in self._done]


# ─────────────────────────────────────────────────────────────
# GPT Vision API 호출
# ─────────────────────────────────────────────────────────────
def parse_gpt_response(response_text: str) -> Tuple[str, float, str]:
    """GPT 응답 JSON 파싱 → (label, confidence, reasoning)"""
    try:
        text = response_text.strip()
        if "```" in text:
            text = text.split("```")[1]
            if text.startswith("json"):
                text = text[4:]
        data   = json.loads(text)
        label  = data.get("label", "").strip().upper()
        if label not in CLASS_NAMES:
            for cn in CLASS_NAMES:
                if cn in label:
                    label = cn
                    break
            else:
                label = "HR"
        confidence = float(data.get("confidence", 0.5))
        reasoning  = str(data.get("reasoning", ""))
        return label, confidence, reasoning
    except Exception:
        for cn in CLASS_NAMES:
            if cn in response_text.upper():
                return cn, 0.25, response_text[:300]
        return "HR", 0.25, response_text[:300]


async def call_gpt_async(
    client: AsyncOpenAI,
    headline: str,
    image_b64: str,
    semaphore: asyncio.Semaphore,
    max_retries: int = 5,
    idx: int = 0,
) -> Tuple[str, float, str]:
    """비동기 GPT Vision API 호출.
    Rate Limit(429) 발생 시 지수 백오프로 자동 대기.
    """
    messages = [{"role": "system", "content": SYSTEM_PROMPT}]
    messages += build_user_message(headline, image_b64)

    async with semaphore:
        for attempt in range(max_retries):
            try:
                resp = await client.chat.completions.create(
                    model=MODEL_NAME,
                    messages=messages,
                    max_completion_tokens=MAX_COMPLETION_TOKENS,
                    response_format={"type": "json_object"},
                )
                return parse_gpt_response(resp.choices[0].message.content)

            except Exception as e:
                err_str = str(e).lower()
                # Rate Limit: 더 오래 대기
                if "429" in err_str or "rate" in err_str:
                    wait = min(60, 5 * (2 ** attempt))
                    print(f"\n  [RateLimit] 샘플 {idx} — {wait}s 대기 후 재시도 "
                          f"({attempt+1}/{max_retries})", file=sys.stderr)
                    await asyncio.sleep(wait)
                # 서버 오류: 짧게 대기
                elif "500" in err_str or "502" in err_str or "503" in err_str:
                    wait = 3 * (attempt + 1)
                    print(f"\n  [ServerErr] 샘플 {idx} — {wait}s 대기 "
                          f"({attempt+1}/{max_retries})", file=sys.stderr)
                    await asyncio.sleep(wait)
                else:
                    wait = 2 ** attempt
                    print(f"\n  [Error] 샘플 {idx}: {e} — {wait}s 대기 "
                          f"({attempt+1}/{max_retries})", file=sys.stderr)
                    await asyncio.sleep(wait)

        # 모든 재시도 실패
        print(f"\n  [Fail] 샘플 {idx} 최종 실패", file=sys.stderr)
        return "HR", 0.0, "API_ERROR"


# ─────────────────────────────────────────────────────────────
# 전체 데이터셋 비동기 평가
# ─────────────────────────────────────────────────────────────
async def run_zeroshot_async(
    df: pd.DataFrame,
    data_root: str,
    concurrency: int,
    api_key: str,
    image_size: int,
    ckpt_manager: CheckpointManager,
) -> List[dict]:
    """멀티모달 test split 비동기 zero-shot 평가.
    - 체크포인트에 이미 있는 샘플은 API 호출 없이 스킵
    - 완료된 결과는 즉시 JSONL에 저장 (중단 안전)
    """
    client    = AsyncOpenAI(api_key=api_key)
    semaphore = asyncio.Semaphore(concurrency)

    total     = len(df)
    n_skip    = sum(1 for i in range(total) if ckpt_manager.is_done(i))
    n_todo    = total - n_skip

    print(f"\n[ZeroShot] 평가 시작")
    print(f"  전체 샘플  : {total}")
    print(f"  이미 완료  : {n_skip} (체크포인트 이어받기)")
    print(f"  새로 요청  : {n_todo}")
    print(f"  모델       : {MODEL_NAME}")
    print(f"  이미지     : detail=auto, {image_size}x{image_size} (harfnet CLIP)")
    print(f"  동시 요청  : {concurrency}\n")

    pbar = _tqdm(total=total, initial=n_skip, desc="[ZeroShot] GPT Vision")

    results_by_idx: Dict[int, dict] = {}
    for i in range(total):
        if ckpt_manager.is_done(i):
            results_by_idx[i] = ckpt_manager.get_done(i)

    queue: asyncio.Queue = asyncio.Queue()
    for i, row in df.iterrows():
        if not ckpt_manager.is_done(i):
            queue.put_nowait((int(i), row))

    async def process_one(i: int, row: pd.Series) -> dict:
        image_b64 = load_image_b64(row["image_path"], data_root, size=image_size)
        if image_b64 is None:
            return {
                "idx":        i,
                "headline":   row["final_headline"],
                "image_path": row["image_path"],
                "true_label": row["4_way_label"],
                "pred_label": "HR",
                "confidence": 0.0,
                "reasoning":  "IMAGE_LOAD_ERROR",
                "img_ok":     False,
            }

        pred_label, conf, reasoning = await call_gpt_async(
            client, row["final_headline"], image_b64,
            semaphore, idx=i,
        )
        return {
            "idx":        i,
            "headline":   row["final_headline"],
            "image_path": row["image_path"],
            "true_label": row["4_way_label"],
            "pred_label": pred_label,
            "confidence": conf,
            "reasoning":  reasoning,
            "img_ok":     True,
        }

    async def worker(wid: int):
        while True:
            try:
                i, row = queue.get_nowait()
            except asyncio.QueueEmpty:
                break
            result = await process_one(i, row)
            await ckpt_manager.save_one(result)
            results_by_idx[i] = result
            queue.task_done()
            pbar.update(1)
            if len(results_by_idx) == n_skip + 1:
                print(f"\n[ZeroShot] 첫 API 응답 완료 (worker {wid})", flush=True)

    workers = [asyncio.create_task(worker(w)) for w in range(concurrency)]
    await asyncio.gather(*workers)
    pbar.close()

    results = [results_by_idx[i] for i in range(total)]

    n_err = sum(1 for r in results if not r.get("img_ok", True))
    n_api_err = sum(1 for r in results if r.get("reasoning") == "API_ERROR")
    if n_err or n_api_err:
        print(f"[ZeroShot] 이미지 로드 실패: {n_err}개 | API 오류: {n_api_err}개")

    return list(results)


# ─────────────────────────────────────────────────────────────
# ─────────────────────────────────────────────────────────────
def compute_metrics(results: List[dict]) -> Dict:
    """4-way / H-A / R-F 메트릭 계산"""
    yt = np.array([CLASS2IDX[r["true_label"]] for r in results])
    yp = np.array([CLASS2IDX.get(r["pred_label"], 0) for r in results])

    # 신뢰도 기반 소프트 확률 근사 (zero-shot은 소프트맥스 없음)
    proba = np.zeros((len(results), 4), dtype=np.float64)
    for i, r in enumerate(results):
        pred_idx = CLASS2IDX.get(r["pred_label"], 0)
        conf     = float(r["confidence"])
        proba[i, pred_idx] = conf
        remaining = (1.0 - conf) / 3.0
        for j in range(4):
            if j != pred_idx:
                proba[i, j] = remaining

    # 4-way
    acc4 = float(accuracy_score(yt, yp))
    f1_4 = float(f1_score(yt, yp, average="macro", zero_division=0))

    # Human vs AI (0,1=Human / 2,3=AI)
    yh, ph = yt // 2, yp // 2
    acc_ha = float(accuracy_score(yh, ph))
    f1_ha  = float(f1_score(yh, ph, average="macro", zero_division=0))

    # Real vs Fake (0,2=Real / 1,3=Fake)
    yr, pr = yt % 2, yp % 2
    acc_rf = float(accuracy_score(yr, pr))
    f1_rf  = float(f1_score(yr, pr, average="macro", zero_division=0))

    # ROC-AUC
    try:
        auc_4 = float(roc_auc_score(yt, proba, multi_class="ovr",
                                    average="macro", labels=[0, 1, 2, 3]))
    except Exception:
        auc_4 = float("nan")
    try:
        auc_ha = float(roc_auc_score(yh, proba[:, 2] + proba[:, 3]))
    except Exception:
        auc_ha = float("nan")
    try:
        auc_rf = float(roc_auc_score(yr, proba[:, 1] + proba[:, 3]))
    except Exception:
        auc_rf = float("nan")

    # Per-class accuracy
    per_class_acc = {}
    for i, cn in enumerate(CLASS_NAMES):
        mask = yt == i
        if mask.sum() > 0:
            per_class_acc[cn] = float((yp[mask] == i).mean())

    return {
        "yt": yt, "yp": yp, "proba": proba,
        "acc4": acc4, "f1_4": f1_4,
        "acc_ha": acc_ha, "f1_ha": f1_ha,
        "acc_rf": acc_rf, "f1_rf": f1_rf,
        "auc_4_ovr_macro": auc_4,
        "auc_ha": auc_ha, "auc_rf": auc_rf,
        "per_class_acc": per_class_acc,
    }


def build_report(results: List[dict], m: Dict, args) -> str:
    """전체 평가 리포트 생성 ("""
    yt, yp = m["yt"], m["yp"]
    yh, ph = yt // 2, yp // 2
    yr, pr = yt % 2, yp % 2
    buf = io.StringIO()

    buf.write("=" * 80 + "\n")
    buf.write(f"  HARFNEWS Zero-Shot Evaluation | Model: {MODEL_NAME}\n")
    buf.write(f"  실행 시각  : {datetime.now().isoformat(timespec='seconds')}\n")
    buf.write(f"  모드       : 멀티모달 (이미지+텍스트, detail=auto, "
              f"{args.image_size}x{args.image_size} harfnet CLIP)\n")
    buf.write(f"  test 샘플  : {len(results)} (전체 {getattr(args, 'n_full', '?')} 중 {TEST_RATIO:.0%})\n")
    n_err = sum(1 for r in results if not r.get("img_ok", True))
    n_api = sum(1 for r in results if r.get("reasoning") == "API_ERROR")
    if n_err:
        buf.write(f"  이미지 오류: {n_err}개\n")
    if n_api:
        buf.write(f"  API 오류   : {n_api}개\n")
    buf.write("=" * 80 + "\n\n")

    buf.write("=== [1] Human vs AI ===\n")
    buf.write(classification_report(yh, ph, target_names=["Human", "AI"],
                                    digits=4, zero_division=0))
    buf.write(f"\n  Accuracy={m['acc_ha']:.4f}  Macro-F1={m['f1_ha']:.4f}  "
              f"ROC-AUC={m['auc_ha']:.4f}\n\n")

    buf.write("=== [2] Real vs Fake ===\n")
    buf.write(classification_report(yr, pr, target_names=["Real", "Fake"],
                                    digits=4, zero_division=0))
    buf.write(f"\n  Accuracy={m['acc_rf']:.4f}  Macro-F1={m['f1_rf']:.4f}  "
              f"ROC-AUC={m['auc_rf']:.4f}\n\n")

    buf.write("=== [3] 4-Way (HR / HF / AR / AF) ===\n")
    buf.write(classification_report(yt, yp, target_names=CLASS_NAMES,
                                    digits=4, zero_division=0))
    buf.write(f"\n  Accuracy={m['acc4']:.4f}  Macro-F1={m['f1_4']:.4f}  "
              f"ROC-AUC(OVR)={m['auc_4_ovr_macro']:.4f}\n\n")

    buf.write("=== [4] 클래스별 정확도 ===\n")
    for cn, acc in m["per_class_acc"].items():
        buf.write(f"  {cn}: {acc:.4f}\n")

    buf.write("\n" + "=" * 80 + "\n")
    buf.write("★ SUMMARY\n")
    buf.write(f"  4-Way  : F1={m['f1_4']:.4f}  AUC={m['auc_4_ovr_macro']:.4f}\n")
    buf.write(f"  H/A    : F1={m['f1_ha']:.4f}  AUC={m['auc_ha']:.4f}\n")
    buf.write(f"  R/F    : F1={m['f1_rf']:.4f}  AUC={m['auc_rf']:.4f}\n")
    buf.write("=" * 80 + "\n")

    return buf.getvalue()


# ─────────────────────────────────────────────────────────────
# 비용 추정
# ─────────────────────────────────────────────────────────────
def print_cost_estimate(n_samples: int, image_size: int):
    """GPT-5-mini 기준 대략적 비용 추정 (참고용)"""
    # detail=auto, 224x224 (harfnet CLIP) → 약 1 tile 수준
    img_tokens_per   = 255          # 224px 기준 추정
    text_tokens_in   = 350          # system + user 텍스트
    text_tokens_out  = 200          # JSON 응답 (gpt-5-mini reasoning 포함)
    total_in  = (text_tokens_in + img_tokens_per) * n_samples
    total_out = text_tokens_out * n_samples

    # gpt-5-mini 가격 (2025년 기준 추정: input $0.15/1M, output $0.60/1M)
    cost_in  = total_in  / 1_000_000 * 0.15
    cost_out = total_out / 1_000_000 * 0.60
    total_cost = cost_in + cost_out


# ─────────────────────────────────────────────────────────────
# 메인
# ─────────────────────────────────────────────────────────────
def main():
    pa = argparse.ArgumentParser(
        description="HARFNEWS Zero-Shot w/ GPT-5-mini (멀티모달 test 20%)"
    )
    pa.add_argument("--csv_path",   default=DEFAULT_CSV_PATH,  help="HARFM.csv 경로")
    pa.add_argument("--data_root",  default=DEFAULT_DATA_ROOT, help="이미지 루트 경로")
    pa.add_argument("--output_dir", default=DEFAULT_OUTPUT,    help="결과 저장 디렉터리")
    pa.add_argument("--concurrency",     type=int, default=8,
                    help="동시 API 요청 수 (기본: 8)")
    pa.add_argument("--image_size",      type=int, default=IMAGE_SIZE,
                    help="이미지 크기 (기본: 224,")
    pa.add_argument("--seed",            type=int, default=SEED)
    pa.add_argument("--no_resume",       action="store_true",
                    help="체크포인트 무시하고 처음부터 재실행")
    pa.add_argument("--yes",             action="store_true",
                    help="비용 확인 프롬프트 자동 승인")
    args = pa.parse_args()

    # API 키: 코드 상단 OPENAI_API_KEY → 환경변수 순으로 사용
    api_key = OPENAI_API_KEY or os.environ.get("OPENAI_API_KEY", "")
    if not api_key or api_key.startswith("sk-여기에"):
        print("[오류] 코드 상단 OPENAI_API_KEY에 실제 키를 입력해주세요.", file=sys.stderr)
        sys.exit(1)

    os.makedirs(args.output_dir, exist_ok=True)
    random.seed(args.seed); np.random.seed(args.seed)

    df_full = load_dataset(args.csv_path, args.data_root, seed=args.seed)
    labels  = [CLASS2IDX[l] for l in df_full["4_way_label"]]
    te_idx  = split_test_indices(labels, seed=args.seed)
    df      = df_full.iloc[te_idx].reset_index(drop=True)
    n_full  = len(df_full)
    n_total = len(df)
    args.n_full = n_full
    print(f"[ZeroShot] test split: {n_total}/{n_full} "
          f"({TEST_RATIO:.0%}, seed={args.seed})")

    # 체크포인트 경로 (csv 기반으로 고정 — 재실행해도 같은 파일)
    ckpt_name    = "harfnews_zeroshot_checkpoint.jsonl"
    ckpt_path    = os.path.join(args.output_dir, ckpt_name)
    ckpt_manager = CheckpointManager(ckpt_path)

    if args.no_resume and os.path.isfile(ckpt_path):
        os.remove(ckpt_path)

    n_done = ckpt_manager.load()
    n_todo = n_total - n_done
    if n_done > 0:
        print(f"[ZeroShot] 체크포인트 복원: {n_done}/{n_total}개 완료, "
              f"{n_todo}개 남음")

    # 비용 추정 + 확인
    print_cost_estimate(n_todo, args.image_size)
    if n_todo > 0 and not args.yes:
        ans = input("계속 진행하시겠습니까? [y/N] ").strip().lower()
        if ans not in ("y", "yes"):
            print("중단.")
            sys.exit(0)

    # 비동기 평가
    start = time.time()
    results = asyncio.run(run_zeroshot_async(
        df, args.data_root,
        concurrency=args.concurrency,
        api_key=api_key,
        image_size=args.image_size,
        ckpt_manager=ckpt_manager,
    ))
    elapsed = time.time() - start

    # idx 순 정렬 (asyncio.gather는 순서 보장하지만 안전하게)
    results.sort(key=lambda r: r["idx"])

    print(f"\n[ZeroShot] 완료 — {elapsed:.1f}초 ({elapsed/60:.1f}분) | "
          f"샘플당 {elapsed/max(len(results),1):.2f}초")

    # ── 메트릭 ──
    m = compute_metrics(results)

    # ── 리포트 출력 ──
    report = build_report(results, m, args)
    print("\n" + report)

    # ── 결과 저장 ──
    ts     = datetime.now().strftime("%Y%m%d_%H%M%S")
    prefix = f"gpt5mini_zeroshot_multimodal_test20_{ts}"

    report_path = os.path.join(args.output_dir, f"{prefix}_report.txt")
    with open(report_path, "w", encoding="utf-8") as f:
        f.write(report)
    print(f"[저장] 리포트     : {report_path}")

    detail_df = pd.DataFrame([{
        "idx":        r["idx"],
        "headline":   r["headline"],
        "image_path": r["image_path"],
        "true_label": r["true_label"],
        "pred_label": r["pred_label"],
        "confidence": r["confidence"],
        "correct":    r["true_label"] == r["pred_label"],
        "ha_correct": (CLASS2IDX[r["true_label"]] // 2) == (CLASS2IDX.get(r["pred_label"], 0) // 2),
        "rf_correct": (CLASS2IDX[r["true_label"]] % 2) == (CLASS2IDX.get(r["pred_label"], 0) % 2),
        "img_ok":     r.get("img_ok", True),
        "reasoning":  r["reasoning"],
    } for r in results])
    csv_path = os.path.join(args.output_dir, f"{prefix}_predictions.csv")
    detail_df.to_csv(csv_path, index=False, encoding="utf-8-sig")
    print(f"[저장] 예측 CSV   : {csv_path}")

    metrics_out = {k: v for k, v in m.items() if k not in ("yt", "yp", "proba")}
    metrics_out.update({
        "model":       MODEL_NAME,
        "n_samples":   n_total,
        "n_full":      n_full,
        "test_ratio":  TEST_RATIO,
        "n_evaluated": len(results),
        "image_size":  args.image_size,
        "detail":      "auto",
        "elapsed_sec": round(elapsed, 2),
    })
    json_path = os.path.join(args.output_dir, f"{prefix}_metrics.json")
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(metrics_out, f, ensure_ascii=False, indent=2)
    print(f"[저장] 메트릭 JSON: {json_path}")
    print(f"[저장] 체크포인트  : {ckpt_path}")

    # ── 최종 요약 ──
    print(f"\n{'='*60}")
    print(f"[GPT-5-mini Zero-Shot | 멀티모달 test 20%] HARFNEWS 평가 결과")
    print(f"  test 샘플 : {n_total} / {n_full} ({TEST_RATIO:.0%})")
    print(f"  4-Way  F1 = {m['f1_4']:.4f}   AUC = {m['auc_4_ovr_macro']:.4f}")
    print(f"  H/A    F1 = {m['f1_ha']:.4f}   AUC = {m['auc_ha']:.4f}")
    print(f"  R/F    F1 = {m['f1_rf']:.4f}   AUC = {m['auc_rf']:.4f}")
    print(f"{'='*60}")


if __name__ == "__main__":
    main()
