"""
HARFNEWS Zero-Shot Evaluation with Qwen/Qwen2.5-VL-7B-Instruct
===============================================================
학습(train) 없이 로컬 GPU에서 Qwen2.5-VL을 이용한 zero-shot 4-way 분류 평가.
클래스: HR (Human Real) / HF (Human Fake) / AR (AI Real) / AF (AI Fake)

   - 배치 추론으로 GPU 효율 극대화
   - 중간 저장(체크포인트) 지원: 중단 후 재실행하면 완료된 샘플 자동 스킵
   - Flash Attention 2 / bfloat16 자동 적용

사용법:
    python harfnet_zeroshot_qwen.py [--options]

주요 옵션:
    --csv_path        HARFM.csv 경로
    --data_root       이미지 루트 경로
    --output_dir      결과 저장 디렉터리
    --model_name      HuggingFace 모델 ID (기본: Qwen/Qwen2.5-VL-7B-Instruct)
    --batch_size      배치 크기 (기본: 4, VRAM에 따라 조정)
    --max_new_tokens  생성 최대 토큰 수 (기본: 256)
    --num_workers     DataLoader 워커 수 (기본: 4)
    --no_resume       체크포인트 무시하고 처음부터 재실행
    --device          cuda / cpu (기본: 자동)
"""

from __future__ import annotations

import argparse
import io
import json
import os
import random
import sys
import time
import warnings
from datetime import datetime
from typing import Dict, List, Optional, Tuple

warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import torch
from PIL import Image
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    f1_score,
    roc_auc_score,
)
from sklearn.model_selection import train_test_split
from torch.utils.data import DataLoader, Dataset
from tqdm import tqdm
from transformers import AutoProcessor, Qwen2_5_VLForConditionalGeneration

# ─────────────────────────────────────────────────────────────
# 상수
# ─────────────────────────────────────────────────────────────
MODEL_NAME_DEFAULT = "Qwen/Qwen2.5-VL-7B-Instruct"
CLASS_NAMES        = ["HR", "HF", "AR", "AF"]
CLASS2IDX          = {c: i for i, c in enumerate(CLASS_NAMES)}

_SCRIPT_DIR       = os.path.dirname(os.path.abspath(__file__))
_FND_ROOT = os.path.abspath(os.path.join(_SCRIPT_DIR, ".."))
DEFAULT_DATA_ROOT = _FND_ROOT
DEFAULT_CSV_PATH  = os.path.join(_FND_ROOT, "HARFM.csv")
DEFAULT_OUTPUT    = os.path.join(_SCRIPT_DIR, "results_zeroshot_qwen")

SEED = 42
TEST_RATIO = 0.2
IMAGE_SIZE = 224


def _tqdm_disable() -> bool:
    return os.environ.get("QWEN_NO_TQDM", "").lower() in ("1", "true", "yes")


def _tqdm_file():
    """tee(2>&1) 로그에는 progress bar 미기록, 터미널(/dev/tty)에만 표시."""
    if _tqdm_disable():
        return None
    try:
        return open("/dev/tty", "w")
    except OSError:
        return None


class _TqdmNoOp:
    def update(self, n: int = 1) -> None:
        pass

    def close(self) -> None:
        pass


def _tqdm(*args, **kwargs):
    if _tqdm_disable():
        return _TqdmNoOp() if not args else args[0]
    fout = _tqdm_file()
    if fout is None:
        return _TqdmNoOp() if not args else args[0]
    kwargs.setdefault("file", fout)
    kwargs.setdefault("dynamic_ncols", True)
    return tqdm(*args, **kwargs)


# ─────────────────────────────────────────────────────────────
# Zero-Shot 프롬프트
# ─────────────────────────────────────────────────────────────
SYSTEM_PROMPT = (
    "You are an expert multimodal news analyst specializing in detecting "
    "AI-generated content and misinformation.\n\n"
    "You will be given a news headline AND its accompanying image. "
    "Analyze BOTH together to classify the article into one of four categories:\n\n"
    "- HR (Human-Real): Written by a human, content is factually true/real\n"
    "- HF (Human-Fake): Written by a human, content is false/fabricated/misleading\n"
    "- AR (AI-Real): Generated by AI, content is factually true/real\n"
    "- AF (AI-Fake): Generated by AI, content is false/fabricated/misleading\n\n"
    "Classification guidelines:\n"
    "[Text/Authorship] AI text: formulaic, syntactically perfect, uniform structure. "
    "Human text: idiosyncratic style, colloquialisms, subtle irregularities.\n"
    "[Text/Veracity] Fake: sensational language, unverifiable claims, logical gaps. "
    "Real: neutral tone, specific verifiable facts.\n"
    "[Image/Authorship] AI image: unnaturally smooth, distorted hands/text/faces, "
    "surreal perfection. Real photo: natural noise, authentic lighting.\n"
    "[Image/Veracity] Mismatch between image context and headline claim. "
    "Manipulated images: inconsistent shadows, blurred edges.\n"
    "[Cross-modal] AF: fluent AI text + AI/manipulated image, factually wrong. "
    "HF: human text + misleading real photo.\n\n"
    "Respond ONLY with a JSON object:\n"
    "{\"label\": \"<HR|HF|AR|AF>\", \"confidence\": <0.0-1.0>, "
    "\"reasoning\": \"<2-3 sentences citing text and image cues>\"}\n"
    "No other text outside the JSON."
)


def build_conversation(headline: str) -> list:
    """Qwen2.5-VL chat 형식 메시지 구성.
    이미지는 processor가 <image> 플레이스홀더로 처리하므로
    content에 {"type": "image"} 항목을 포함.
    """
    user_text = (
        f"Analyze the following news article using BOTH the headline and the image.\n\n"
        f"**Headline:** {headline}\n\n"
        f"Consider: (1) writing style for authorship, "
        f"(2) factual plausibility, "
        f"(3) image authenticity, "
        f"(4) consistency between image and headline.\n\n"
        f"Respond ONLY with the JSON object."
    )
    return [
        {"role": "system", "content": SYSTEM_PROMPT},
        {
            "role": "user",
            "content": [
                {"type": "image"},          # 이미지 플레이스홀더
                {"type": "text", "text": user_text},
            ],
        },
    ]


# ─────────────────────────────────────────────────────────────
# 유틸
# ─────────────────────────────────────────────────────────────
def resolve_image_path(p: str, data_root: str) -> str:
    p = (p or "").strip()
    if not p:
        return ""
    if os.path.isabs(p) and os.path.isfile(p):
        return p
    return os.path.join(os.path.abspath(data_root), p)


def preprocess_image_harfnet(img: Image.Image, size: int = IMAGE_SIZE) -> Image.Image:
    """짧은 변 size 리사이즈 후 CenterCrop size."""
    w, h = img.size
    if w < h:
        new_w, new_h = size, int(round(h * size / w))
    else:
        new_w, new_h = int(round(w * size / h)), size
    img = img.resize((new_w, new_h), Image.LANCZOS)
    left = (new_w - size) // 2
    top  = (new_h - size) // 2
    return img.crop((left, top, left + size, top + size))


def set_seed(s: int = SEED):
    random.seed(s)
    np.random.seed(s)
    torch.manual_seed(s)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(s)


def parse_model_response(text: str) -> Tuple[str, float, str]:
    """모델 출력 텍스트 → (label, confidence, reasoning)"""
    try:
        t = text.strip()
        # JSON 블록 추출
        if "```" in t:
            t = t.split("```")[1]
            t = t.lstrip("json").strip()
        # 중괄호 범위만 추출
        start = t.find("{")
        end   = t.rfind("}") + 1
        if start >= 0 and end > start:
            t = t[start:end]
        data  = json.loads(t)
        label = str(data.get("label", "")).strip().upper()
        if label not in CLASS_NAMES:
            for cn in CLASS_NAMES:
                if cn in label:
                    label = cn
                    break
            else:
                label = "HR"
        confidence = float(data.get("confidence", 0.5))
        reasoning  = str(data.get("reasoning", ""))
        return label, confidence, reasoning
    except Exception:
        # 텍스트에서 레이블 직접 탐색
        text_up = text.upper()
        for cn in CLASS_NAMES:
            if cn in text_up:
                return cn, 0.25, text[:300]
        return "HR", 0.25, text[:300]


# ─────────────────────────────────────────────────────────────
# 데이터 로딩
# ─────────────────────────────────────────────────────────────
def load_full_multimodal_df(csv_path: str, data_root: str) -> pd.DataFrame:
    """이미지+텍스트 둘 다 존재하는 전체 샘플 로딩"""
    print(f"[Qwen ZeroShot] CSV 로딩: {csv_path}")
    df = pd.read_csv(
        csv_path,
        usecols=["final_headline", "image_path", "4_way_label"],
        low_memory=False,
    )
    df = df.dropna(subset=["final_headline", "4_way_label"])
    for c in ["final_headline", "image_path", "4_way_label"]:
        df[c] = df[c].fillna("").astype(str).str.strip()

    df = df[df["4_way_label"].isin(CLASS_NAMES)].reset_index(drop=True)
    n_before = len(df)
    print(f"[Qwen ZeroShot] 이미지 유효성 검사 중 ({n_before}행)...")

    def is_multimodal(row) -> bool:
        if not row.final_headline:
            return False
        full = resolve_image_path(row.image_path, data_root)
        return bool(full) and os.path.isfile(full)

    mask = [is_multimodal(r) for r in _tqdm(
        df.itertuples(), total=n_before, desc="  이미지 유효성 검사")]
    df = df[mask].reset_index(drop=True)
    n_after = len(df)

    lc = df["4_way_label"].value_counts().to_dict()
    print(f"[Qwen ZeroShot] {n_before}행 → 멀티모달 유효 {n_after}행 "
          f"({n_before - n_after}행 스킵)")
    print(f"[Qwen ZeroShot] 레이블 분포: {lc}")

    if n_after == 0:
        raise ValueError("멀티모달 유효 샘플 없음. --csv_path/--data_root 확인.")
    return df


def split_test_indices(labels: List[int], seed: int = SEED) -> List[int]:
    """..."""
    idx = np.arange(len(labels))
    y   = np.array(labels)
    _, te, _, _ = train_test_split(
        idx, y, test_size=TEST_RATIO, stratify=y, random_state=seed,
    )
    return te.tolist()


# ─────────────────────────────────────────────────────────────
# Dataset
# ─────────────────────────────────────────────────────────────
class HARFMultimodalDataset(Dataset):
    """(headline, image_path, label, idx) 반환 Dataset.
    이미지 로드 실패 시 회색 더미 이미지로 대체 + img_ok=False 표시.
    """

    def __init__(self, df: pd.DataFrame, data_root: str, image_size: int = IMAGE_SIZE):
        self.df         = df.reset_index(drop=True)
        self.data_root  = os.path.abspath(data_root)
        self.image_size = image_size

    def __len__(self) -> int:
        return len(self.df)

    def _load_image(self, rel_path: str) -> Tuple[Image.Image, bool]:
        try:
            full = resolve_image_path(rel_path, self.data_root)
            if not full or not os.path.isfile(full):
                return Image.new("RGB", (self.image_size, self.image_size),
                                 (127, 127, 127)), False
            img = preprocess_image_harfnet(
                Image.open(full).convert("RGB"), size=self.image_size)
            return img, True
        except Exception:
            return Image.new("RGB", (self.image_size, self.image_size),
                             (127, 127, 127)), False

    def __getitem__(self, idx: int) -> dict:
        row         = self.df.iloc[idx]
        img, img_ok = self._load_image(row["image_path"])
        return {
            "idx":       idx,
            "headline":  row["final_headline"],
            "image":     img,                       # PIL Image (collate에서 처리)
            "true_label": row["4_way_label"],
            "image_path": row["image_path"],
            "img_ok":    img_ok,
        }


def collate_fn(batch: list) -> dict:
    """PIL Image는 리스트로 유지, 나머지는 리스트/텐서로 묶음."""
    return {
        "idx":        [b["idx"]        for b in batch],
        "headline":   [b["headline"]   for b in batch],
        "image":      [b["image"]      for b in batch],   # List[PIL.Image]
        "true_label": [b["true_label"] for b in batch],
        "image_path": [b["image_path"] for b in batch],
        "img_ok":     [b["img_ok"]     for b in batch],
    }


# ─────────────────────────────────────────────────────────────
# 체크포인트
# ─────────────────────────────────────────────────────────────
class CheckpointManager:
    """완료된 샘플을 JSONL에 즉시 저장 / 재실행 시 자동 스킵."""

    def __init__(self, path: str):
        self.path  = path
        self._done: Dict[int, dict] = {}

    def load(self) -> int:
        if not os.path.isfile(self.path):
            return 0
        with open(self.path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    r = json.loads(line)
                    self._done[r["idx"]] = r
                except Exception:
                    continue
        return len(self._done)

    def is_done(self, idx: int) -> bool:
        return idx in self._done

    def save_batch(self, results: List[dict]):
        with open(self.path, "a", encoding="utf-8") as f:
            for r in results:
                self._done[r["idx"]] = r
                f.write(json.dumps(r, ensure_ascii=False) + "\n")

    def get(self, idx: int) -> Optional[dict]:
        return self._done.get(idx)

    def all_results(self, n: int) -> List[dict]:
        return [self._done[i] for i in range(n) if i in self._done]


# ─────────────────────────────────────────────────────────────
# 모델 로딩
# ─────────────────────────────────────────────────────────────
def load_model_and_processor(
    model_name: str, device: str
) -> Tuple[Qwen2_5_VLForConditionalGeneration, AutoProcessor]:
    """Qwen2.5-VL 모델 및 프로세서 로딩.
    - bfloat16 + Flash Attention 2 자동 적용 (GPU)
    - CPU 폴백 시 float32
    """
    print(f"[Qwen ZeroShot] 모델 로딩: {model_name}")
    use_gpu = device.startswith("cuda") and torch.cuda.is_available()

    load_kw: dict = {
        "trust_remote_code": True,
    }
    if use_gpu:
        load_kw["torch_dtype"]  = torch.bfloat16
        load_kw["device_map"]   = "auto"         # 멀티 GPU 자동 분산
        # Flash Attention 2 사용 가능하면 적용 (없어도 동작)
        try:
            import flash_attn  # noqa: F401
            load_kw["attn_implementation"] = "flash_attention_2"
            print("[Qwen ZeroShot] Flash Attention 2 활성화")
        except ImportError:
            print("[Qwen ZeroShot] Flash Attention 2 미설치 → 기본 attention 사용")
    else:
        load_kw["torch_dtype"] = torch.float32
        load_kw["device_map"]  = "cpu"

    model = Qwen2_5_VLForConditionalGeneration.from_pretrained(
        model_name, **load_kw
    )
    model.eval()

    # 프로세서: 이미지 해상도 범위 설정 (최소 256, 최대 1280)
    processor = AutoProcessor.from_pretrained(
        model_name,
        trust_remote_code=True,
        min_pixels=256 * 28 * 28,
        max_pixels=1280 * 28 * 28,
    )

    gpu_info = ""
    if use_gpu:
        n_gpu = torch.cuda.device_count()
        vram  = sum(torch.cuda.get_device_properties(i).total_memory
                    for i in range(n_gpu)) / 1024**3
        gpu_info = f" | GPU×{n_gpu} ({vram:.1f} GB)"
    print(f"[Qwen ZeroShot] 모델 준비 완료{gpu_info}")
    return model, processor


# ─────────────────────────────────────────────────────────────
# 배치 추론
# ─────────────────────────────────────────────────────────────
@torch.inference_mode()
def infer_batch(
    model: Qwen2_5_VLForConditionalGeneration,
    processor: AutoProcessor,
    headlines: List[str],
    images: List[Image.Image],
    device: str,
    max_new_tokens: int = 256,
) -> List[Tuple[str, float, str]]:
    """하나의 배치에 대해 Qwen2.5-VL 추론 수행.
    반환: [(label, confidence, reasoning), ...]
    """
    # 각 샘플의 conversation 템플릿 구성
    conversations = [build_conversation(h) for h in headlines]

    # chat template 적용 → 텍스트 프롬프트 생성
    texts = [
        processor.apply_chat_template(
            conv,
            tokenize=False,
            add_generation_prompt=True,
        )
        for conv in conversations
    ]

    # 프로세서로 토큰화 + 이미지 전처리
    # padding=True: 배치 내 길이 통일
    inputs = processor(
        text=texts,
        images=images,
        padding=True,
        return_tensors="pt",
    )

    # GPU로 이동
    target_device = next(model.parameters()).device
    inputs = {k: v.to(target_device) for k, v in inputs.items()}

    # 생성
    generated_ids = model.generate(
        **inputs,
        max_new_tokens=max_new_tokens,
        do_sample=False,         # greedy (zero-shot 재현성)
        temperature=None,
        top_p=None,
        pad_token_id=processor.tokenizer.eos_token_id,
    )

    # 입력 토큰 제거 → 생성된 부분만 추출
    input_len = inputs["input_ids"].shape[1]
    output_ids = generated_ids[:, input_len:]

    # 디코딩
    decoded = processor.batch_decode(
        output_ids,
        skip_special_tokens=True,
        clean_up_tokenization_spaces=False,
    )

    return [parse_model_response(text) for text in decoded]


# ─────────────────────────────────────────────────────────────
# 전체 평가 루프
# ─────────────────────────────────────────────────────────────
def run_evaluation(
    model: Qwen2_5_VLForConditionalGeneration,
    processor: AutoProcessor,
    df: pd.DataFrame,
    data_root: str,
    device: str,
    args,
    ckpt: CheckpointManager,
) -> List[dict]:
    """전체 멀티모달 데이터셋 배치 평가."""

    dataset    = HARFMultimodalDataset(df, data_root, image_size=args.image_size)
    dataloader = DataLoader(
        dataset,
        batch_size=args.batch_size,
        shuffle=False,          # 순서 유지 (체크포인트 idx 기준)
        num_workers=args.num_workers,
        collate_fn=collate_fn,
        pin_memory=device.startswith("cuda"),
    )

    n_total = len(df)
    n_done  = sum(1 for i in range(n_total) if ckpt.is_done(i))
    n_todo  = n_total - n_done

    print(f"\n[Qwen ZeroShot] 평가 시작")
    print(f"  test 샘플  : {n_total}")
    print(f"  이미 완료  : {n_done} (체크포인트 이어받기)")
    print(f"  새로 처리  : {n_todo}")
    print(f"  배치 크기  : {args.batch_size}")
    print(f"  이미지 크기: {args.image_size}x{args.image_size} (harfnet CLIP)\n")

    pbar = _tqdm(total=n_total, initial=n_done, desc="[Qwen ZeroShot] 추론")

    for batch in dataloader:
        idxs      = batch["idx"]          # List[int]
        headlines = batch["headline"]      # List[str]
        images    = batch["image"]         # List[PIL.Image]
        labels    = batch["true_label"]    # List[str]
        paths     = batch["image_path"]    # List[str]
        img_oks   = batch["img_ok"]        # List[bool]

        # 이미 완료된 샘플이 포함된 배치는 건너뜀
        # 미완료 샘플만 추려서 추론 (부분 배치)
        todo_pos = [i for i, idx in enumerate(idxs) if not ckpt.is_done(idx)]

        if not todo_pos:
            pbar.update(len(idxs))
            continue

        # 미완료 샘플만 슬라이싱
        todo_idx      = [idxs[i]      for i in todo_pos]
        todo_headlines= [headlines[i]  for i in todo_pos]
        todo_images   = [images[i]     for i in todo_pos]
        todo_labels   = [labels[i]     for i in todo_pos]
        todo_paths    = [paths[i]      for i in todo_pos]
        todo_img_oks  = [img_oks[i]    for i in todo_pos]

        # 추론
        try:
            preds = infer_batch(
                model, processor,
                todo_headlines, todo_images,
                device, args.max_new_tokens,
            )
        except torch.cuda.OutOfMemoryError:
            print("\n[OOM] VRAM 부족 — --batch_size를 줄이거나 --image_size를 낮추세요.",
                  file=sys.stderr)
            torch.cuda.empty_cache()
            # 1개씩 재시도
            preds = []
            for h, img in zip(todo_headlines, todo_images):
                try:
                    p = infer_batch(model, processor, [h], [img],
                                    device, args.max_new_tokens)
                    preds.extend(p)
                except Exception as e:
                    print(f"  [Fail] {e}", file=sys.stderr)
                    preds.append(("HR", 0.0, "INFER_ERROR"))

        # 결과 저장
        batch_results = []
        for pos, (pred_label, conf, reasoning) in enumerate(preds):
            batch_results.append({
                "idx":        todo_idx[pos],
                "headline":   todo_headlines[pos],
                "image_path": todo_paths[pos],
                "true_label": todo_labels[pos],
                "pred_label": pred_label,
                "confidence": conf,
                "reasoning":  reasoning,
                "img_ok":     todo_img_oks[pos],
            })

        ckpt.save_batch(batch_results)
        pbar.update(len(idxs))

    pbar.close()

    results = ckpt.all_results(n_total)
    n_err   = sum(1 for r in results if not r.get("img_ok", True))
    n_inf_err = sum(1 for r in results if r.get("reasoning") == "INFER_ERROR")
    if n_err or n_inf_err:
        print(f"[Qwen ZeroShot] 이미지 로드 실패: {n_err}개 | "
              f"추론 오류: {n_inf_err}개")
    return results


# ─────────────────────────────────────────────────────────────
# ─────────────────────────────────────────────────────────────
def compute_metrics(results: List[dict]) -> Dict:
    yt = np.array([CLASS2IDX[r["true_label"]] for r in results])
    yp = np.array([CLASS2IDX.get(r["pred_label"], 0) for r in results])

    proba = np.zeros((len(results), 4), dtype=np.float64)
    for i, r in enumerate(results):
        pred_idx = CLASS2IDX.get(r["pred_label"], 0)
        conf     = float(r["confidence"])
        proba[i, pred_idx] = conf
        rem = (1.0 - conf) / 3.0
        for j in range(4):
            if j != pred_idx:
                proba[i, j] = rem

    acc4  = float(accuracy_score(yt, yp))
    f1_4  = float(f1_score(yt, yp, average="macro", zero_division=0))
    yh, ph = yt // 2, yp // 2
    acc_ha = float(accuracy_score(yh, ph))
    f1_ha  = float(f1_score(yh, ph, average="macro", zero_division=0))
    yr, pr = yt % 2, yp % 2
    acc_rf = float(accuracy_score(yr, pr))
    f1_rf  = float(f1_score(yr, pr, average="macro", zero_division=0))

    try:
        auc_4 = float(roc_auc_score(yt, proba, multi_class="ovr",
                                    average="macro", labels=[0, 1, 2, 3]))
    except Exception:
        auc_4 = float("nan")
    try:
        auc_ha = float(roc_auc_score(yh, proba[:, 2] + proba[:, 3]))
    except Exception:
        auc_ha = float("nan")
    try:
        auc_rf = float(roc_auc_score(yr, proba[:, 1] + proba[:, 3]))
    except Exception:
        auc_rf = float("nan")

    per_class_acc = {}
    for i, cn in enumerate(CLASS_NAMES):
        mask = yt == i
        if mask.sum() > 0:
            per_class_acc[cn] = float((yp[mask] == i).mean())

    return {
        "yt": yt, "yp": yp, "proba": proba,
        "acc4": acc4, "f1_4": f1_4,
        "acc_ha": acc_ha, "f1_ha": f1_ha,
        "acc_rf": acc_rf, "f1_rf": f1_rf,
        "auc_4_ovr_macro": auc_4,
        "auc_ha": auc_ha, "auc_rf": auc_rf,
        "per_class_acc": per_class_acc,
    }


def build_report(results: List[dict], m: Dict, args) -> str:
    yt, yp = m["yt"], m["yp"]
    yh, ph = yt // 2, yp // 2
    yr, pr = yt % 2, yp % 2
    buf = io.StringIO()

    buf.write("=" * 80 + "\n")
    buf.write(f"  HARFNEWS Zero-Shot Evaluation | Model: {args.model_name}\n")
    buf.write(f"  실행 시각  : {datetime.now().isoformat(timespec='seconds')}\n")
    buf.write(f"  모드       : 멀티모달 (이미지+텍스트, max={args.image_size}px, "
              f"batch={args.batch_size})\n")
    buf.write(
        f"  test 샘플  : {len(results)} "
        f"(전체 {getattr(args, 'n_full', '?')} 중 {TEST_RATIO:.0%})\n"
    )
    n_err = sum(1 for r in results if not r.get("img_ok", True))
    n_inf = sum(1 for r in results if r.get("reasoning") == "INFER_ERROR")
    if n_err: buf.write(f"  이미지 오류: {n_err}개\n")
    if n_inf: buf.write(f"  추론 오류  : {n_inf}개\n")
    buf.write("=" * 80 + "\n\n")

    buf.write("=== [1] Human vs AI ===\n")
    buf.write(classification_report(yh, ph, target_names=["Human", "AI"],
                                    digits=4, zero_division=0))
    buf.write(f"\n  Accuracy={m['acc_ha']:.4f}  Macro-F1={m['f1_ha']:.4f}  "
              f"ROC-AUC={m['auc_ha']:.4f}\n\n")

    buf.write("=== [2] Real vs Fake ===\n")
    buf.write(classification_report(yr, pr, target_names=["Real", "Fake"],
                                    digits=4, zero_division=0))
    buf.write(f"\n  Accuracy={m['acc_rf']:.4f}  Macro-F1={m['f1_rf']:.4f}  "
              f"ROC-AUC={m['auc_rf']:.4f}\n\n")

    buf.write("=== [3] 4-Way (HR / HF / AR / AF) ===\n")
    buf.write(classification_report(yt, yp, target_names=CLASS_NAMES,
                                    digits=4, zero_division=0))
    buf.write(f"\n  Accuracy={m['acc4']:.4f}  Macro-F1={m['f1_4']:.4f}  "
              f"ROC-AUC(OVR)={m['auc_4_ovr_macro']:.4f}\n\n")

    buf.write("=== [4] 클래스별 정확도 ===\n")
    for cn, acc in m["per_class_acc"].items():
        buf.write(f"  {cn}: {acc:.4f}\n")

    buf.write("\n" + "=" * 80 + "\n")
    buf.write("★ SUMMARY\n")
    buf.write(f"  4-Way  : F1={m['f1_4']:.4f}  AUC={m['auc_4_ovr_macro']:.4f}\n")
    buf.write(f"  H/A    : F1={m['f1_ha']:.4f}  AUC={m['auc_ha']:.4f}\n")
    buf.write(f"  R/F    : F1={m['f1_rf']:.4f}  AUC={m['auc_rf']:.4f}\n")
    buf.write("=" * 80 + "\n")
    return buf.getvalue()


# ─────────────────────────────────────────────────────────────
# 메인
# ─────────────────────────────────────────────────────────────
def main():
    pa = argparse.ArgumentParser(
        description="HARFNEWS Zero-Shot w/ Qwen2.5-VL (멀티모달 test 20%)"
    )
    pa.add_argument("--csv_path",      default=DEFAULT_CSV_PATH)
    pa.add_argument("--data_root",     default=DEFAULT_DATA_ROOT)
    pa.add_argument("--output_dir",    default=DEFAULT_OUTPUT)
    pa.add_argument("--model_name",    default=MODEL_NAME_DEFAULT,
                    help="HuggingFace 모델 ID")
    pa.add_argument("--batch_size",    type=int, default=4,
                    help="배치 크기 (VRAM 24GB 기준 기본값 4)")
    pa.add_argument("--max_new_tokens",type=int, default=256)
    pa.add_argument("--image_size",    type=int, default=IMAGE_SIZE,
                    help="이미지 크기 (기본: 224,")
    pa.add_argument("--num_workers",   type=int, default=4)
    pa.add_argument("--device",        default="cuda" if torch.cuda.is_available() else "cpu")
    pa.add_argument("--seed",          type=int, default=SEED)
    pa.add_argument("--no_resume",     action="store_true",
                    help="체크포인트 무시하고 처음부터 재실행")
    args = pa.parse_args()

    set_seed(args.seed)
    os.makedirs(args.output_dir, exist_ok=True)

    # GPU 정보 출력
    if torch.cuda.is_available():
        for i in range(torch.cuda.device_count()):
            p = torch.cuda.get_device_properties(i)
            print(f"[GPU {i}] {p.name} | VRAM {p.total_memory/1024**3:.1f} GB")
    else:
        print("[경고] CUDA 미감지 — CPU로 실행 (매우 느림)")

    df_full = load_full_multimodal_df(args.csv_path, args.data_root)
    labels  = [CLASS2IDX[l] for l in df_full["4_way_label"]]
    te_idx  = split_test_indices(labels, seed=args.seed)
    df      = df_full.iloc[te_idx].reset_index(drop=True)
    n_full  = len(df_full)
    args.n_full = n_full
    print(f"[Qwen ZeroShot] test split: {len(df)}/{n_full} "
          f"({TEST_RATIO:.0%}, seed={args.seed})")

    # 체크포인트
    ckpt_path = os.path.join(args.output_dir, "qwen_zeroshot_checkpoint.jsonl")
    ckpt      = CheckpointManager(ckpt_path)
    if args.no_resume and os.path.isfile(ckpt_path):
        print(f"[Qwen ZeroShot] --no_resume: 기존 체크포인트 삭제")
        os.remove(ckpt_path)
    n_done = ckpt.load()
    if n_done > 0:
        print(f"[Qwen ZeroShot] 체크포인트 복원: {n_done}/{len(df)}개 완료")

    # 모델 로딩
    model, processor = load_model_and_processor(args.model_name, args.device)

    # 평가
    start   = time.time()
    results = run_evaluation(model, processor, df, args.data_root,
                             args.device, args, ckpt)
    elapsed = time.time() - start

    results.sort(key=lambda r: r["idx"])
    print(f"\n[Qwen ZeroShot] 완료 — {elapsed:.1f}초 ({elapsed/60:.1f}분) | "
          f"샘플당 {elapsed/max(len(results),1):.2f}초")

    # 메트릭 & 리포트
    m      = compute_metrics(results)
    report = build_report(results, m, args)
    print("\n" + report)

    # 저장
    ts     = datetime.now().strftime("%Y%m%d_%H%M%S")
    prefix = f"qwen_zeroshot_multimodal_test20_{ts}"

    rp = os.path.join(args.output_dir, f"{prefix}_report.txt")
    with open(rp, "w", encoding="utf-8") as f:
        f.write(report)
    print(f"[저장] 리포트     : {rp}")

    detail_df = pd.DataFrame([{
        "idx":        r["idx"],
        "headline":   r["headline"],
        "image_path": r["image_path"],
        "true_label": r["true_label"],
        "pred_label": r["pred_label"],
        "confidence": r["confidence"],
        "correct":    r["true_label"] == r["pred_label"],
        "ha_correct": (CLASS2IDX[r["true_label"]] // 2) == (CLASS2IDX.get(r["pred_label"], 0) // 2),
        "rf_correct": (CLASS2IDX[r["true_label"]] % 2) == (CLASS2IDX.get(r["pred_label"], 0) % 2),
        "img_ok":     r.get("img_ok", True),
        "reasoning":  r["reasoning"],
    } for r in results])
    cp = os.path.join(args.output_dir, f"{prefix}_predictions.csv")
    detail_df.to_csv(cp, index=False, encoding="utf-8-sig")
    print(f"[저장] 예측 CSV   : {cp}")

    metrics_out = {k: v for k, v in m.items() if k not in ("yt", "yp", "proba")}
    metrics_out.update({
        "model":        args.model_name,
        "n_samples":    len(results),
        "n_full":       n_full,
        "test_ratio":   TEST_RATIO,
        "batch_size":   args.batch_size,
        "image_size":   args.image_size,
        "elapsed_sec":  round(elapsed, 2),
    })
    jp = os.path.join(args.output_dir, f"{prefix}_metrics.json")
    with open(jp, "w", encoding="utf-8") as f:
        json.dump(metrics_out, f, ensure_ascii=False, indent=2)
    print(f"[저장] 메트릭 JSON: {jp}")
    print(f"[저장] 체크포인트  : {ckpt_path}")

    print(f"\n{'='*60}")
    print(f"[Qwen2.5-VL Zero-Shot | 멀티모달 test 20%] HARFNEWS 평가 결과")
    print(f"  test 샘플 : {len(results)} / {n_full} ({TEST_RATIO:.0%})")
    print(f"  4-Way  F1 = {m['f1_4']:.4f}   AUC = {m['auc_4_ovr_macro']:.4f}")
    print(f"  H/A    F1 = {m['f1_ha']:.4f}   AUC = {m['auc_ha']:.4f}")
    print(f"  R/F    F1 = {m['f1_rf']:.4f}   AUC = {m['auc_rf']:.4f}")
    print(f"{'='*60}")


if __name__ == "__main__":
    main()